modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="mechacraft"
version="1.0.0"
displayName="MechaCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="edmun, MCreator"

[[dependencies.mechacraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"




